### ISSUE TITLE
When a library is being imported, the import ignores custom paths defined in `require` metadata

### ISSUE THREAD

**Issue by mildas** [beakerlib/beakerlib#143]
When a library is required by other library, it ignores custom path definition in metadata.

Example
`main.fmf` (library for test script):
```
summary: Library used to import in test script
component:
- scap-security-guide
framework: beakerlib
require:
- libxml2
- url: https://src.fedoraproject.org/tests/scap-security-guide.git
  name: /Library/scap-common
  nick: scap-common-lib
```
Load function (library for test script, it uses custom import to reflect path overridden by `nick` metadata):
```
scapResLibraryLoaded() {
    rlImport "scap-common-lib/scap-common" || rlDie "Failed to import scap-common library"
    return 0
}
```

`rlImport "scap-common-lib/scap-common"` is successful as it searches custom path and finds the library. However, when a library is being loaded and `require` from metadata are being installed, it tries to find `scap-common` again but using `scap-security-guide/scap-common`. And as it ignores `nick`, it doesn't look to `scap-common-lib` directory.
