### ISSUE TITLE
cat: /var/tmp/tmt/run-075/plans/package_update-swtpm/execute/data/Setup: No such file or directory

### ISSUE THREAD

**Issue by kkaarreell** [beakerlib/beakerlib#148]
When running a test from `tmt` plan I can see following errors
```
how: tmt
order: 50
exit-first: False
    test: Configure local repository with RPMs from Brew
        out: /usr/share/beakerlib/journal.sh: line 146: $__INTERNAL_PHASE_STATUSES: ambiguous redirect
        out: /usr/share/beakerlib/journal.sh: line 147: $__INTERNAL_ASSERT_STATUSES: ambiguous redirect
        out: cat: /var/tmp/tmt/run-075/plans/package_update-swtpm/execute/data/Setup: No such file or directory
        out: cat: swtpm: No such file or directory
        out: cat: repo/setup/configure-repo-with-rpms-from-brew/default/PHASE_STATUSES: No such file or directory
        out: cat: /var/tmp/tmt/run-075/plans/package_update-swtpm/execute/data/Setup: No such file or directory
        out: cat: swtpm: No such file or directory
        out: cat: repo/setup/configure-repo-with-rpms-from-brew/default/ASSERT_STATUSES: No such file or directory
        out: 
        out: ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
        out: ::   Setup
        out: ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
```
It is caused by the fact that `discover` phase names contain spaces, e.g.
```
discover:
  - name: Setup swtpm
```
It seems that this is causing issue in beakerlib. In tmt this has been also a problem but has been addressed through https://github.com/teemtee/tmt/issues/1520

I have: beakerlib-1.29.3-1.el9.noarch
