### ISSUE TITLE
tmt tests misconfigured

### ISSUE THREAD

**Issue by LecrisUT** [beakerlib/beakerlib#159]
The tests defined in `/plans/tmt` are running the tests of `tmt`, not those of this repo. There is a bit of overlap, but shouldn't there be tests defined for this repo as well that run `make test` or the individual test files?

**Comment by sopos** [comment]
Right, there are no tests like these written specifically for beakerlib. There's and internal test suite `make test` but there are still some failures there. That's our debt.

**Comment by LecrisUT** [comment]
If I enable these tests, can someone take a look at them to fix them?

**Comment by LecrisUT** [comment]
I think we can do it with:
```yaml
# /palns/unit_tests.fmf
summary: Unit tests for beakerlib
discover:
  how: shell
  tests:
  - name: Beakerlib unit tests
    test: make test
```
